#!/bin/bash
# gen-root.bash — Regenerate root MKplusCAC.lean with all module imports
#
# Usage: bash gen-root.bash
#
# Scans MKplusCAC/ for all .lean files (excluding _template.lean),
# sorts them, and rewrites MKplusCAC.lean with the full import list.
# The root file is unlocked before writing and re-locked if it was locked.

set -e

# Detect project name
PROJECT_NAME=$(grep 'package «' lakefile.lean 2>/dev/null | sed 's/.*«\(.*\)».*/\1/')
if [ -z "$PROJECT_NAME" ]; then
    echo "Error: Could not detect project name from lakefile.lean"
    exit 1
fi

ROOT_FILE="${PROJECT_NAME}.lean"
MODULE_DIR="${PROJECT_NAME}"
YEAR=$(date +%Y)
AUTHOR=$(git config user.name 2>/dev/null || echo "Your Name")

# Collect all .lean files, excluding _template.lean, sorted
IMPORTS=()
while IFS= read -r FILE; do
    BASENAME=$(basename "$FILE" .lean)
    [ "$BASENAME" = "_template" ] && continue
    # Convert file path to import name: MKplusCAC/Foo/Bar.lean -> MKplusCAC.Foo.Bar
    REL="${FILE#${MODULE_DIR}/}"
    REL="${REL%.lean}"
    IMPORT_NAME="${PROJECT_NAME}.${REL//\//.}"
    IMPORTS+=("$IMPORT_NAME")
done < <(find "$MODULE_DIR" -name "*.lean" ! -name "_template.lean" | sort)

if [ ${#IMPORTS[@]} -eq 0 ]; then
    echo "Warning: No modules found in $MODULE_DIR/"
fi

# Unlock root if locked
WAS_LOCKED=false
if grep -Fxq "$ROOT_FILE" locked_files.txt 2>/dev/null; then
    WAS_LOCKED=true
    bash git-lock.bash unlock "$ROOT_FILE"
fi

# Write root file
{
    echo "/-"
    echo "Copyright (c) ${YEAR}. All rights reserved."
    echo "Author: ${AUTHOR}"
    echo "License: MIT"
    echo "-/"
    echo ""
    echo "-- Root module: auto-generated by gen-root.bash"
    echo "-- Run 'bash gen-root.bash' after adding or removing modules."
    echo ""
    for IMPORT in "${IMPORTS[@]}"; do
        echo "import ${IMPORT}"
    done
} > "$ROOT_FILE"

echo "✅ Generated $ROOT_FILE with ${#IMPORTS[@]} imports:"
for IMPORT in "${IMPORTS[@]}"; do
    echo "   $IMPORT"
done

# Re-lock if it was locked
if [ "$WAS_LOCKED" = true ]; then
    bash git-lock.bash lock "$ROOT_FILE"
fi
