/-
Copyright (c) 2026. All rights reserved.
Author: Your Name
License: MIT
-/

-- Root module: auto-generated by gen-root.bash
-- Run 'bash gen-root.bash' after adding or removing modules.

import MKplusCAC.MKplusCACAxioms
import MKplusCAC.Prelim
import MKplusCAC.Relations
